### PR TITLE
Actually guard against missing emails

### LINKED ISSUE #190: Login Error If Emails Not Found
The login jobs introduced by #182 are failing periodically with:

> no implicit conversion of String into Integer
>
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 []
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 block in perform
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 each
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 detect
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 perform

The failing users show a Not Found payload instead of the expected array -

```json
          emails: {
            "message": "Not Found",
            "documentation_url": "https://developer.github.com/v3"
          }
```

### PR DESCRIPTION
**Pull request by dahlbyk**
Actually fixes #190. The `respond_to?` check added by #191 doesn't actually exclude a `Hash`.

### CODE REVIEW

File: vendor/engines/saas/app/jobs/login_private_job.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 class LoginPrivateJob < ActiveJob::Base
 
   def perform(params)
-    if params['emails'].respond_to?('detect')
+    if params['emails'].is_a?(Array)
       email = params['emails'].detect{|e| e['primary'] == true}
       params['user']['email'] = email['email']
```
Comment (discorick) [inline vendor/engines/saas/app/jobs/login_private_job.rb]: This will throw if `email` is an empty array, I suppose we can do something like `params['emails'].is_a?(Array) && params['emails'].size`

Comment (dahlbyk) [inline vendor/engines/saas/app/jobs/login_private_job.rb]: What about `params['emails'].detect{|e| e['primary'] == true} || {}`?

**Comment by rauhryan** [comment]
haha, ok 

sorry for jumping the gun

:shipit:

File: vendor/engines/saas/app/jobs/login_private_job.rb (hunk 1 above)
Comment (discorick) [inline vendor/engines/saas/app/jobs/login_private_job.rb]: That would also work !
