### PR TITLE
Fixes regressions on the account page (close on overlay click, close w/ ESC)

### LINKED ISSUE #167: [SAAS] Load Details method throws exception if not part of an organization in accounts
Whenever a user attempts to navigate to a organization at `settings/profile` that they are not a part of, they get thrown a white screen of death. This should probably show them a message stating that they are not a part of the organization / do not have permission to edit, and perhaps send them a link back to their main profile page.

uploads/d166edc5-c140-4a77-9430-13612d7c7960/blob

Closed by huboard/huboard-web#158

### PR DESCRIPTION
**Pull request by iheanyi**
Finally figured it out, some action handlers got misplaced during the refactor, but I figured out where to place them and that fixed everything. 

Fixes #167

### CODE REVIEW

**Comment by discorick** [comment]
Nice!!

Does this close PR's #158 and #189 ?

**Comment by dahlbyk** [comment]
> Does this close PR's #158 and #189 ?

Yes, at this point we should just work from this one and merging it will automatically close the other two.

File: vendor/engines/saas/app/controllers/saas/coupons_controller.rb [hunk 1]
```diff
@@ -12,7 +12,7 @@ def redeem
       query = Queries::CouchCustomer.get_cust(params[:id], couch)
       doc = QueryHandler.exec(&query)
       return render json: {success: false, message: "Couldn't find couch record: #{plan_doc.id}"} unless doc
-      plan_doc = doc.rows.first.value
+      plan_doc = doc
```
Comment (dahlbyk) [inline vendor/engines/saas/app/controllers/saas/coupons_controller.rb]: FYI, this was pulled out into https://github.com/huboard/huboard-web/pull/166

**Comment by dahlbyk** [comment]
Hey @discorick, while we're here can you fix this overlap issue?

firefox_2016-03-22_10-08-40

**Comment by discorick** [comment]
This happens when you resize the browser ?

**Comment by dahlbyk** [comment]
> This happens when you resize the browser ?

Yep, between ~786 and 980px.

**Comment by discorick** [comment]
Ok, ill take a look!

**Comment by dahlbyk** [comment]
Also, upgrading an account with Stripe is not actually working on this PR branch:

> Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js

It works on [another PR](https://huboard-rails-pr-243.herokuapp.com/settings/profile), so it seems unlikely to be a quirk with review apps. Not sure if this is related to 58c1ce03ff7627bc7e0d751a002320f8694c1f12?

**Comment by discorick** [comment]
I would guess 58c1ce0 is the culprit!

**Comment by discorick** [comment]
After removing `ember-cli-dotenv` and setting the `STRIPE_PUBLISHABLE_API` in `config/environment` based on the the `process.env` key store; charges seem to be working and validating successfully. 

@iheanyi, do you mind peaking at fe80d38 and letting me know if it sets off any alarm bells ?

**Comment by discorick** [comment]
Fixed :D 

image

File: app/assets/stylesheets/_account.scss [hunk 2]
```diff
@@ -15,9 +14,15 @@
     display: none;
   }
 
+  .new-account {
+    display: flex;
```
Comment (dahlbyk) [inline app/assets/stylesheets/_account.scss]: I usually see `@include display(flex)` and/or `@include flex(1)` rather than plain `display: flex`. Thoughts?

File: ember-accounts/app/templates/settings/user-profile.hbs [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+  <div class="nav-section billing-section">
+    <div class="widget-body">
+      {{x-history model=model}}
+    </div>
+  </div>
+</div>
+
+<div class="question-label">
+  <strong>Have questions?</strong> Email us anytime at support@huboard.com
+</div>
```
Comment (dahlbyk) [inline ember-accounts/app/templates/settings/user-profile.hbs]: Can we tack this block at the bottom of `profile.hbs`?

File: ember-accounts/app/templates/settings.hbs [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+      {{#link-to 'settings.user-profile' tagName='li' herf=false}}
+        {{#link-to "settings.user-profile"}}
+        <img height="24" width="24" src={{model.user.gravatar_url}}
+                         alt="{{model.user.login}} Avatar">
+        {{model.user.login}}
+        {{/link-to}}
+      {{/link-to}}
+
+      {{#each model.orgs as |org|}}
+        {{#link-to 'settings.profile' org tagName='li' herf=false}}
```
Comment (dahlbyk) [inline ember-accounts/app/templates/settings.hbs]: `herf=false`: should this be `href=false` (also on line 6)?

File: ember-accounts/app/templates/not-authorized.hbs [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+
+      <div class="orgs">
+      {{#each model.orgs as |org|}}
+          {{#link-to 'settings.profile' org}}
+              <div class="org-item">
+                <img class="org-image" height="72" width="72" src={{org.gravatar_url}}
+                                 alt="{{org.login}} Avatar" />
+                <h4 class="org-label">{{org.login}}</h4>
+              </div>
```
Comment (dahlbyk) [inline ember-accounts/app/templates/not-authorized.hbs]: Styling of this block is a little weird - inconsistent widths, and note the small underline between the logos.
chrome_2016-03-23_15-52-46

File: ember-accounts/app/templates/components/x-history.hbs [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+    <tbody>
+
+      {{#each model.history.charges as |charge|}}
+      <tr>
+        <td>{{stripe-date charge.created }}</td>
+        <td>{{ charge.receipt_email }}</td>
+        <td>{{stripe-money charge.amount }}</td>
+        <td class="text-right">    
+         {{#if charge.paid}}
+          <a href="/settings/invoices/{{unbound charge.invoice }}">HTML</a> | <a
```
Comment (dahlbyk) [inline ember-accounts/app/templates/components/x-history.hbs]: Does not seem to be in scope for this PR, but I made a mental note that HTML invoices would ideally have a link back to the receipt list.

File: ember-accounts/app/templates/components/x-account.hbs [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+    <p><strong> Something went wrong retrieving your account information!
+    </strong></p>
+    <p> 
+      Please try again later, or <a href="mailto:support@huboard.com">Contact Support </a>
+    </p>
+  </div>
+  <div class={{if purchaseWithTrial 'active' 'disabled'}}>
+    <p><strong> Subscription Active! </strong></p>
+    <p> 
+      As your trial is still in effect, you will not be charged until: {{stripe-date plan.trial_end}}
```
Comment (dahlbyk) [inline ember-accounts/app/templates/components/x-account.hbs]: I'm pretty sure I saw this message after upgrading a trial I had just started, but clicking back into the same org showed "Subscription Active" and a new receipt showed up. Are you able to reproduce?

File: ember-accounts/app/templates/components/x-account.hbs [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+
+  <div class={{if noAccount 'new-account' 'disabled'}}>
+    <div>
+      <p>
+        <strong>All Accounts</strong> receive a <strong>15 day free trial</strong>.
+      </p>
+    </div>
+    <div class='trial-form'>
+      <form {{action "activateTrial" on="submit"}}>
+        {{input type="email" placeholder="Email Address" name="billing_email" value=emailBinding required="required"}}
```
Comment (dahlbyk) [inline ember-accounts/app/templates/components/x-account.hbs]: I noticed the Stripe form email field is pre-filled with what seems to be the org billing email. Could we fill the same in here?

File: ember-accounts/app/templates/components/update-email.hbs [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+      <button type="button" class="close" {{action 'close'}} data-dismiss="modal" aria-hidden="true">×</button>
+      Update Account Email
+    </div>
+    <div class="modal-body">
+      <fieldset>
+        <div class="form-row full">
+          <label>
+            <span>Email Address</span>
+          </label>
+          {{input value=email type="email" required=true}}
```
Comment (dahlbyk) [inline ember-accounts/app/templates/components/update-email.hbs]: Often fields like this are pre-filled with the current value. Is that possible here?

File: ember-accounts/app/templates/components/x-history.hbs (hunk 6 above)
Comment (dahlbyk) [inline ember-accounts/app/templates/components/x-history.hbs]: Or just open the invoice in a new tab/window.

**Comment by dahlbyk** [comment]
Left a few other comments/questions. Almost there!

File: app/assets/stylesheets/_account.scss (hunk 2 above)
Comment (discorick) [inline app/assets/stylesheets/_account.scss]: Yeah you are right, I think this should be `@include display(flex)`

File: ember-accounts/app/templates/settings.hbs (hunk 4 above)
Comment (discorick) [inline ember-accounts/app/templates/settings.hbs]: damn, good eye

File: ember-accounts/app/templates/components/x-history.hbs (hunk 6 above)
Comment (discorick) [inline ember-accounts/app/templates/components/x-history.hbs]: `target='_blank'` should do the trick

File: ember-accounts/app/templates/components/x-account.hbs (hunk 7 above)
Comment (discorick) [inline ember-accounts/app/templates/components/x-account.hbs]: It's a one time note - if I remember that state is (nearly) impossible to derive from the data, so on upgrade the message displays. On refresh it just falls back to "subscription active"

File: ember-accounts/app/templates/components/x-account.hbs (hunk 8 above)
Comment (discorick) [inline ember-accounts/app/templates/components/x-account.hbs]: We could, I personally like it blank better - I could be convinced either way though.

File: ember-accounts/app/templates/components/update-email.hbs (hunk 9 above)
Comment (discorick) [inline ember-accounts/app/templates/components/update-email.hbs]: Again.. another field that I personally prefer to be blank

File: ember-accounts/app/templates/not-authorized.hbs (hunk 5 above)
Comment (discorick) [inline ember-accounts/app/templates/not-authorized.hbs]: Interesting, I can take a stab at it for sure.

**Comment by dahlbyk** [comment]
> > I'm pretty sure I saw this message after upgrading a trial I had just started, but clicking back into the same org showed "Subscription Active" and a new receipt showed up. Are you able to reproduce?
> 
> It's a one time note - if I remember that state is (nearly) impossible to derive from the data, so on upgrade the message displays. On refresh it just falls back to "subscription active"

I'm more concerned about the correctness of the message. It said "you won't be billed until the trial is up" but then a receipt showed up.

**Comment by discorick** [comment]
>> > I'm pretty sure I saw this message after upgrading a trial I had just started, but clicking back into the same org showed "Subscription Active" and a new receipt showed up. Are you able to reproduce?
>> 
>> It's a one time note - if I remember that state is (nearly) impossible to derive from the data, so on upgrade the message displays. On refresh it just falls back to "subscription active"

>I'm more concerned about the correctness of the message. It said "you won't be billed until the trial is up" but then a receipt showed up.

Gotcha, I would say this is probably out-of-scope on this PR - alert semantics should be addressed seperately IMHO

File: ember-accounts/app/templates/components/x-account.hbs (hunk 8 above)
Comment (dahlbyk) [inline ember-accounts/app/templates/components/x-account.hbs]: Rationale is that one click is easier than type + click. I would guess for most orgs the billing contact for GitHub is also the one that would be responsible for paying for HuBoard.

That said, this is the kind of thing we could A/B test too. Leave it for now.

File: ember-accounts/app/templates/components/update-email.hbs (hunk 9 above)
Comment (dahlbyk) [inline ember-accounts/app/templates/components/update-email.hbs]: That's fine, leave it.

File: ember-accounts/app/templates/settings/profile.hbs [hunk 10]
```diff
@@ -12,3 +12,7 @@
     </div>
   </div>
 </div>
+
+<div class="question-label">
+  <strong>Have questions?</strong> Email us anytime at <a href='mailto:support@huboard.com'> support@huboard.com </a>
```
Comment (dahlbyk) [inline ember-accounts/app/templates/settings/profile.hbs]: Some browsers are dumb about leading/trailing whitespace and anchor tags. Trim?

File: ember-accounts/app/templates/settings/user-profile.hbs [hunk 11]
```diff
@@ -14,5 +14,5 @@
 </div>
 
 <div class="question-label">
-  <strong>Have questions?</strong> Email us anytime at support@huboard.com
+  <strong>Have questions?</strong> Email us anytime at <a href='mailto:support@huboard.com'> support@huboard.com </a>
```
Comment (dahlbyk) [inline ember-accounts/app/templates/settings/user-profile.hbs]: Some browsers are dumb about leading/trailing whitespace and anchor tags. Trim?

:+1: for adding `mailto:`!

**Comment by dahlbyk** [comment]
> Gotcha, I would say this is probably out-of-scope on this PR - alert semantics should be addressed seperately IMHO

That's fine, just asking the questions while we're here since we don't touch this part of the app often.

File: ember-accounts/app/templates/settings/profile.hbs (hunk 10 above)
Comment (discorick) [inline ember-accounts/app/templates/settings/profile.hbs]: Which whitespace are you pointing out? The ws before and following `support@huboard.com` ?

Comment (dahlbyk) [inline ember-accounts/app/templates/settings/profile.hbs]: Si

**Comment by dahlbyk** [comment]
> Adds consistent styling to the accounts/not-authorized org buttons
> Wraps rows of orgs, fixes minor graphical issues

These look good.

Anything else you wanted to look at here, or should we :shipit:?

**Comment by discorick** [comment]
I just removed the trailing/leading white spaces, otherwise it looks good to :ship: to me!
